name: CI

on:
  push:
    branches:
      - tomee-7.0.x
  pull_request:
    branches:
      - tomee-7.0.x
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: joschi/setup-jdk@v2
        with:
          java-version: '8'

      - name: Create tmp dirs
        run: mkdir -p /tmp/tomee-trunk-ubuntu-jvm8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkstyle
        run: mvn help:system checkstyle:check -Pstyle
        env:
          MAVEN_OPTS: -Xmx1536m

      - name: Pmd
        run: mvn help:system pmd:check -Pstyle
        env:
          MAVEN_OPTS: -Xmx1536m

      - name: Compile
        run: mvn help:system -e --show-version --update-snapshots -Djava.io.tmpdir=/tmp/tomee-trunk-ubuntu-jvm8 --fail-at-end clean install -Pall-adapters
        env:
          MAVEN_OPTS: -Xmx1536m

